"""make_author_prompt_text_optional

Revision ID: 2184c688a263
Revises: 703a2e04b426
Create Date: 2025-10-21 20:02:30.138981

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2184c688a263"
down_revision: Union[str, Sequence[str], None] = "703a2e04b426"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("authors", "prompt_text", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("authors", "prompt_text", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
