"""remove_unused_recovery_fields

Revision ID: 703a2e04b426
Revises: b1c14ad946f9
Create Date: 2025-10-18 23:59:04.520628

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "703a2e04b426"
down_revision: Union[str, Sequence[str], None] = "b1c14ad946f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tokens_s0_mint_timestamp"), table_name="tokens_s0")
    op.drop_column("tokens_s0", "mint_timestamp")
    op.drop_column("tokens_s0", "minter_address")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Columns recreated with nullable=True for rollback safety (data loss acceptable per spec)
    op.add_column(
        "tokens_s0",
        sa.Column("minter_address", sa.VARCHAR(length=42), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tokens_s0",
        sa.Column("mint_timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix_tokens_s0_mint_timestamp"), "tokens_s0", ["mint_timestamp"], unique=False
    )
    # ### end Alembic commands ###
