"""add_reveal_tx_hash_to_tokens

Revision ID: b1c14ad946f9
Revises: ccadb7da1897
Create Date: 2025-10-17 17:15:40.033990

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1c14ad946f9"
down_revision: Union[str, Sequence[str], None] = "ccadb7da1897"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tokens_s0",
        sa.Column("reveal_tx_hash", sqlmodel.sql.sqltypes.AutoString(length=66), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tokens_s0", "reveal_tx_hash")
    # ### end Alembic commands ###
