"""add_image_generation_fields

Revision ID: ccadb7da1897
Revises: ac0fccec2b6e
Create Date: 2025-10-17 13:49:44.045850

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccadb7da1897"
down_revision: Union[str, Sequence[str], None] = "ac0fccec2b6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tokens_s0", sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "tokens_s0",
        sa.Column("generation_attempts", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "tokens_s0",
        sa.Column("generation_error", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tokens_s0", "generation_error")
    op.drop_column("tokens_s0", "generation_attempts")
    op.drop_column("tokens_s0", "image_url")
    # ### end Alembic commands ###
